import 'package:flutter/material.dart';
import '../../services/vendor_service.dart';

class BusinessVerificationScreen extends StatefulWidget {
  const BusinessVerificationScreen({super.key});
  @override State<BusinessVerificationScreen> createState() => _BusinessVerificationScreenState();
}

class _BusinessVerificationScreenState extends State<BusinessVerificationScreen> {
  final service = VendorService(); final gstin = TextEditingController(); final business = TextEditingController(); final account = TextEditingController(); final confirm = TextEditingController(); final ifsc = TextEditingController(); final name = TextEditingController();
  Map<String, dynamic> status = {}; bool loading = true; bool busy = false; String? message;
  @override void initState() { super.initState(); _load(); }
  Future<void> _load() async { try { final r = await service.getBusinessVerification(); if (mounted) setState(() => status = Map<String, dynamic>.from(r['data'] ?? r)); } catch (e) { if (mounted) setState(() => message = 'Could not load verification status.'); } finally { if (mounted) setState(() => loading = false); } }
  Future<void> _run(Future<Map<String, dynamic>> Function() action) async { setState(() { busy = true; message = null; }); try { final r = await action(); setState(() => status = Map<String, dynamic>.from(r['data'] ?? r)); } catch (_) { setState(() => message = 'Verification is temporarily unavailable. Please retry safely.'); } finally { setState(() => busy = false); } }
  InputDecoration _dec(String label) => InputDecoration(labelText: label, border: const OutlineInputBorder());
  @override Widget build(BuildContext context) { if (loading) return const Scaffold(body: Center(child: CircularProgressIndicator())); return Scaffold(appBar: AppBar(title: const Text('Business verification')), body: ListView(padding: const EdgeInsets.all(16), children: [if (message != null) Text(message!, style: const TextStyle(color: Colors.red)), Text('Overall: ${status['overall_kyb_status'] ?? 'NOT_STARTED'}', style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold)), const SizedBox(height: 16), Card(child: Padding(padding: const EdgeInsets.all(16), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [const Text('GSTIN', style: TextStyle(fontWeight: FontWeight.bold)), Text('Status: ${status['gstin_status'] ?? 'NOT_STARTED'}'), const SizedBox(height: 12), TextField(controller: gstin, decoration: _dec('GSTIN'), textCapitalization: TextCapitalization.characters), const SizedBox(height: 8), TextField(controller: business, decoration: _dec('Business name (optional)')), const SizedBox(height: 12), ElevatedButton(onPressed: busy ? null : () => _run(() => service.verifyGstin(gstin.text, businessName: business.text)), child: const Text('Verify GSTIN'))]))), const SizedBox(height: 12), Card(child: Padding(padding: const EdgeInsets.all(16), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [const Text('Bank account', style: TextStyle(fontWeight: FontWeight.bold)), Text('Status: ${status['bank_verification_status'] ?? 'NOT_STARTED'} · ${status['bank_account_masked'] ?? 'Not linked'}'), const SizedBox(height: 12), TextField(controller: account, decoration: _dec('Account number'), obscureText: true), const SizedBox(height: 8), TextField(controller: confirm, decoration: _dec('Confirm account number'), obscureText: true), const SizedBox(height: 8), TextField(controller: ifsc, decoration: _dec('IFSC'), textCapitalization: TextCapitalization.characters), const SizedBox(height: 8), TextField(controller: name, decoration: _dec('Account holder name (optional)')), const SizedBox(height: 12), ElevatedButton(onPressed: busy ? null : () => _run(() => service.verifyBank(account: account.text, confirmation: confirm.text, ifsc: ifsc.text, name: name.text)), child: const Text('Verify bank account'))]))), const SizedBox(height: 12), OutlinedButton(onPressed: busy ? null : () => _run(service.requestBusinessReverification), child: const Text('Request reverification'))])); }
  @override void dispose() { for (final c in [gstin, business, account, confirm, ifsc, name]) { c.dispose(); } super.dispose(); }
}
